### ISSUE TITLE
Making it work with splits?

### ISSUE THREAD

**Issue by for-coursera** [gcmt/taboo.vim#13]
Is it possible that `taboo` would reflect switches between splits in a tab? 

For now, it seems it only captures the name (and the modification status) of the first buffer opened in a tab - i.e., I see no reaction in tab's name if I split the window, switch to that newly created split and then open another file there.

**Comment by simonsmith** [comment]
If you use vim-airline then taboo has an integration where it shows the buffer name on the right hand side:

<img width="973" alt="screen shot 2016-03-30 at 15 24 08" src="https://cloud.githubusercontent.com/assets/360703/14145364/829869e4-f68b-11e5-8d44-2e40ef5740ab.png">
