### ISSUE TITLE
vundle update claim git errors

### ISSUE THREAD

**Issue by ranska** [gcmt/taboo.vim#5]
Hi I have this message when i update
don't know from where it come
Error detected while processing /Users/ranska/.vim/bundle/taboo.vim/plugin/taboo.vim:
line    3:
E488: Trailing characters: <<<<<<< HEAD
line   17:
E488: Trailing characters: =======
line  596:
E171: Missing :endif
Press ENTER or type command to continue

**Comment by gcmt** [comment]
Hi, unfortunately I'm not able to reproduce this issue. Does this happen whenever you open Vim or just during the plugin update? Can you provide some more details such as Vim version, platform, etc? Thanks
