### ISSUE TITLE
Restore tab titles with obsession.vim

### ISSUE THREAD

**Issue by deshtop** [gcmt/taboo.vim#9]
I'm using obsession.vim to restore vim sessions, but the tab titles set with taboo are not restored. Some time ago [i asked the obsession.vim developer about the possibility to restore tab titles and he responded that this is not only an obsession issue](https://github.com/tpope/vim-obsession/issues/23).
Would it be much work for you to make this possible? Thanks in advance.

**Comment by gcmt** [comment]
Be sure to have the following line in your `.vimrc`
```vim
set sessionoptions+=globals
```

**Comment by deshtop** [comment]
Perfect, thanks a bunch!
